# 🏦 Predicción de la Suscripción de Clientes a Depósitos a Plazo mediante Machine Learning

### Proyecto de Ciencia de Datos para Optimizar Campañas de Marketing Bancario

---

**👤 Autor:** María Isabel Durango

**🎓 Rol:** Estudiante de Ciencia de Datos

**📌 Tipo de proyecto:** Machine Learning Supervisado – Clasificación Binaria

**📂 Dataset:** Bank Marketing Dataset (UCI Machine Learning Repository)

**📖 Metodología:** CRISP-DM

🛠 Tecnologías utilizadas

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- Scikit-Learn
- Jupyter Notebook

## 📑 Índice

1️⃣ Comprensión del negocio

2️⃣ Comprensión de los datos

3️⃣ Preparación de los datos

4️⃣ Análisis Exploratorio de Datos (EDA)

5️⃣ Ingeniería de Características

6️⃣ Modelado

7️⃣ Evaluación

8️⃣ Conclusiones

9️⃣ Trabajo Futuro

# 1️⃣ Comprensión del Negocio

## 📖 Contexto del negocio

Las instituciones financieras invierten grandes cantidades de recursos en campañas de marketing con el objetivo de promocionar productos financieros, como los depósitos a plazo fijo.

Estas campañas suelen realizarse mediante llamadas telefónicas a potenciales clientes, por lo que es fundamental identificar previamente qué personas tienen mayor probabilidad de aceptar la oferta.

Contar con un modelo predictivo permite optimizar la estrategia comercial, reducir costos operativos y aumentar la efectividad de las campañas de marketing.

---

## 🚨 Problema del negocio

Las campañas de marketing telefónico implican un alto costo económico y de tiempo.

Contactar a todos los clientes disponibles no resulta eficiente, ya que la mayoría no aceptará la oferta.

La entidad financiera necesita una herramienta que permita identificar, antes de realizar la llamada, qué clientes presentan una mayor probabilidad de suscribirse a un depósito a plazo.

---

## 🎯 Objetivo del negocio

Desarrollar un modelo de Machine Learning capaz de predecir si un cliente aceptará o no un depósito a plazo, permitiendo priorizar aquellos clientes con mayor probabilidad de conversión y optimizar la inversión en campañas de marketing.

---

## 🤖 Objetivo del modelo 

Construir, entrenar y comparar diferentes algoritmos de clasificación para seleccionar el modelo con mejor desempeño predictivo, manteniendo un equilibrio entre precisión, capacidad de generalización e interpretabilidad.

---

## 🔄 Metodología CRISP-DM

Este proyecto sigue la metodología CRISP-DM, uno de los estándares más utilizados en proyectos de Ciencia de Datos.

El proyecto se desarrollará siguiendo las siguientes fases:

📌 Comprensión del negocio

📊 Comprensión de los datos

🧹 Preparación de los datos

📈 Análisis Exploratorio de Datos (EDA)

⚙️ Ingeniería de Características

🤖 Modelado

📉 Evaluación

🚀 Conclusiones y recomendaciones

In [13]:
# =============================================================================
# Standard library imports
# =============================================================================
import warnings
warnings.filterwarnings('ignore')  # Suppress non-critical warnings

# =============================================================================
# Data manipulation
# =============================================================================
import pandas as pd
import numpy as np

# =============================================================================
# Visualization
# =============================================================================
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns

# =============================================================================
# Display configuration
# =============================================================================
pd.set_option('display.max_columns', None)   # Show all columns in outputs
pd.set_option('display.max_rows', 100)       # Show up to 100 rows
pd.set_option('display.float_format', '{:.4f}'.format)  # 4 decimal places

# =============================================================================
# Visual style — single consistent theme for the entire notebook
# =============================================================================
PALETTE = ['#2C5F8A', '#E8734A', '#4CAF7D', '#9B59B6', '#F39C12']
sns.set_theme(
    style='whitegrid',          # Clean grid, professional look
    palette=PALETTE,            # Custom color palette (consistent throughout)
    font='DejaVu Sans',         # Standard readable font
    font_scale=1.1              # Slightly larger text for readability
)
plt.rcParams['figure.figsize'] = (12, 6)    # Default figure size
plt.rcParams['figure.dpi'] = 100            # Resolution
plt.rcParams['axes.titlesize'] = 14         # Title font size
plt.rcParams['axes.labelsize'] = 12         # Axis label font size

print("✅ Libraries imported and configuration applied successfully")
print(f"   pandas  : {pd.__version__}")
print(f"   numpy   : {np.__version__}")
print(f"   seaborn : {sns.__version__}")
print(f"   matplotlib: {plt.matplotlib.__version__}")

✅ Libraries imported and configuration applied successfully
   pandas  : 3.0.3
   numpy   : 2.5.0
   seaborn : 0.13.2
   matplotlib: 3.11.0

In [3]:
# Ruta del dataset
data_path = "../data/raw/bank-additional-full.csv"

# Cargar datos
df = pd.read_csv(data_path, sep=";")

print("Dataset cargado correctamente.")

Dataset cargado correctamente.

In [5]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,261,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,149,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,226,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,151,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,307,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

### ⚠️ Nota importante: Variable `duration`

La variable `duration` mide la duración en segundos de la última llamada telefónica con el cliente.

Aunque tiene alta correlación con el target `y`, **será excluida del modelo predictivo** por la siguiente razón:

> En el momento real de uso del modelo —es decir, cuando el agente decide **a quién llamar**—, 
> la llamada todavía no ha ocurrido. Por tanto, la duración de esa llamada es desconocida.

Incluir `duration` en el modelo sería una forma de **data leakage**: 
estaríamos usando información del futuro para predecir el presente, 
lo que haría que el modelo parezca mejor de lo que realmente es en producción.

**Referencia**: Los propios autores del dataset (Moro et al., 2014) reconocen esta limitación 
explícitamente en su paper original.

`duration` se mantiene en el dataset durante el EDA para análisis exploratorio, 
pero será **eliminada antes del entrenamiento de cualquier modelo**.

In [6]:
print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")

Filas: 41188
Columnas: 21

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  str
 2   marital         41188 non-null  str
 3   education       41188 non-null  str
 4   default         41188 non-null  str
 5   housing         41188 non-null  str
 6   loan            41188 non-null  str
 7   contact         41188 non-null  str
 8   month           41188 non-null  str
 9   day_of_week     41188 non-null  str
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  str
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  str
dtypes: float64(5), int64(5), str(11)
memory usage: 6.6 MB

In [8]:
df.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [14]:
# Descriptive statistics for numeric variables
print("=== Numeric Variables ===")
display(df.describe(include=[np.number]).T)  # .T transposes for easier reading

print("\n=== Categorical Variables ===")
# Use select_dtypes to avoid Pandas 2.x deprecation warning
categorical_cols = df.select_dtypes(exclude=[np.number]).columns
display(df[categorical_cols].describe())

=== Numeric Variables ===

,count,mean,std,min,25%,50%,75%,max
age,41188.0000,40.0241,10.4212,17.0000,32.0000,38.0000,47.0000,98.0000
duration,41188.0000,258.2850,259.2792,0.0000,102.0000,180.0000,319.0000,4918.0000
campaign,41188.0000,2.5676,2.7700,1.0000,1.0000,2.0000,3.0000,56.0000
pdays,41188.0000,962.4755,186.9109,0.0000,999.0000,999.0000,999.0000,999.0000
previous,41188.0000,0.1730,0.4949,0.0000,0.0000,0.0000,0.0000,7.0000
emp.var.rate,41188.0000,0.0819,1.5710,-3.4000,-1.8000,1.1000,1.4000,1.4000
cons.price.idx,41188.0000,93.5757,0.5788,92.2010,93.0750,93.7490,93.9940,94.7670
cons.conf.idx,41188.0000,-40.5026,4.6282,-50.8000,-42.7000,-41.8000,-36.4000,-26.9000
euribor3m,41188.0000,3.6213,1.7344,0.6340,1.3440,4.8570,4.9610,5.0450
nr.employed,41188.0000,5167.0359,72.2515,4963.6000,5099.1000,5191.0000,5228.1000,5228.1000

=== Categorical Variables ===

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,y
count,41188,41188,41188,41188,41188,41188,41188,41188,41188,41188,41188
unique,12,4,8,3,3,3,2,10,5,3,2
top,admin.,married,university.degree,no,yes,no,cellular,may,thu,nonexistent,no
freq,10422,24928,12168,32588,21576,33950,26144,13769,8623,35563,36548

In [17]:
df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [18]:
# =============================================================================
# Analysis of 'unknown' values
# IMPORTANT: In this dataset, missing values are encoded as the string "unknown"
# They do NOT appear as NaN, so isnull() does not detect them.
# We must identify and quantify them explicitly.
# =============================================================================

print("=== 'unknown' values per column ===\n")

unknown_counts = {}
for col in df.select_dtypes(exclude=[np.number]).columns:
    count = (df[col] == 'unknown').sum()
    if count > 0:
        pct = count / len(df) * 100
        unknown_counts[col] = {'count': count, 'percentage': pct}
        print(f"  {col:<15} → {count:>5} unknowns ({pct:.2f}%)")

if not unknown_counts:
    print("  No 'unknown' values found in categorical columns.")

print(f"\nTotal rows: {len(df):,}")
print("\n⚠️  NOTE: These are NOT NaN values — they are explicit 'unknown' strings.")
print("    Strategy: Treat 'unknown' as a separate valid category.")
print("    Reason: The fact that a value is unknown IS information in itself.")
print("    We will NOT drop these rows — this decision will be justified in the cleaning phase.")

=== 'unknown' values per column ===

  job             →   330 unknowns (0.80%)
  marital         →    80 unknowns (0.19%)
  education       →  1731 unknowns (4.20%)
  default         →  8597 unknowns (20.87%)
  housing         →   990 unknowns (2.40%)
  loan            →   990 unknowns (2.40%)

Total rows: 41,188

⚠️  NOTE: These are NOT NaN values — they are explicit 'unknown' strings.
    Strategy: Treat 'unknown' as a separate valid category.
    Reason: The fact that a value is unknown IS information in itself.
    We will NOT drop these rows — this decision will be justified in the cleaning phase.

In [20]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='str')